// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurnoDoSiriCascudo.Infra.Dados.Contexto;

#nullable disable

namespace TurnoDoSiriCascudo.Infra.Dados.Migrations
{
    [DbContext(typeof(TurnoDoSiriCascudoContexto))]
    partial class TurnoDoSiriCascudoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.ClienteEntidade.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoPedido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("QuantidadePedido")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid?>("UsuarioAtualizadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioCriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("TB_Clientes", (string)null);
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.IngredienteEntidade.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeIngrediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioAtualizadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioCriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("TB_Ingredientes", (string)null);
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.IngredienteProdutoEntidade.IngredienteProduto", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeIngrediente")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("TB_IngredientesProdutos", (string)null);
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.PedidoEntidade.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroPedido")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<Guid?>("UsuarioAtualizadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioCriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("TB_Pedidos", (string)null);
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.ProdutoEntidade.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("UsuarioAtualizadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioCriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("TB_Produtos", (string)null);
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.ProdutoPedidoEntidade.ProdutoPedido", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeProduto")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("TB_ProdutosPedidos", (string)null);
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.UsuarioEntidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PapelUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("TB_Usuarios", (string)null);
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.ClienteEntidade.Cliente", b =>
                {
                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.UsuarioEntidade.Usuario", "UsuarioCriador")
                        .WithMany("ClientesCadastrados")
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.IngredienteEntidade.Ingrediente", b =>
                {
                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.UsuarioEntidade.Usuario", "UsuarioCriador")
                        .WithMany("IngredientesCadastrados")
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.IngredienteProdutoEntidade.IngredienteProduto", b =>
                {
                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.IngredienteEntidade.Ingrediente", "Ingrediente")
                        .WithMany("IngredientesProdutos")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.ProdutoEntidade.Produto", "Produto")
                        .WithMany("IngredientesProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.PedidoEntidade.Pedido", b =>
                {
                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.ClienteEntidade.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.UsuarioEntidade.Usuario", "UsuarioCriador")
                        .WithMany("PedidosCadastrados")
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.ProdutoEntidade.Produto", b =>
                {
                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.UsuarioEntidade.Usuario", "UsuarioCriador")
                        .WithMany("ProdutosCadastrados")
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.ProdutoPedidoEntidade.ProdutoPedido", b =>
                {
                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.PedidoEntidade.Pedido", "Pedido")
                        .WithMany("ProdutosPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnoDoSiriCascudo.Dominio.Entidades.ProdutoEntidade.Produto", "Produto")
                        .WithMany("ProdutosPedidos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.ClienteEntidade.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.IngredienteEntidade.Ingrediente", b =>
                {
                    b.Navigation("IngredientesProdutos");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.PedidoEntidade.Pedido", b =>
                {
                    b.Navigation("ProdutosPedidos");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.ProdutoEntidade.Produto", b =>
                {
                    b.Navigation("IngredientesProdutos");

                    b.Navigation("ProdutosPedidos");
                });

            modelBuilder.Entity("TurnoDoSiriCascudo.Dominio.Entidades.UsuarioEntidade.Usuario", b =>
                {
                    b.Navigation("ClientesCadastrados");

                    b.Navigation("IngredientesCadastrados");

                    b.Navigation("PedidosCadastrados");

                    b.Navigation("ProdutosCadastrados");
                });
#pragma warning restore 612, 618
        }
    }
}
